### ISSUE TITLE
Buttons, can we simplify some of the params?

### ISSUE THREAD

**Issue by pat270** [metal/metal-clay-components#11]
We have params for css classes `block`, `size`, `style`. Can we let the user define these css classes through `elementClasses`?

We have params for attributes `disabled`, `href`, `name`, `type`, `value`. Can we let the user define these attributes through a single property like `htmlAttributes`? That way we don't limit anyone to just these attributes.

**Comment by robframpton** [comment]
One advantage of keeping them as their own separate params is if a parent component needs to dynamically update one of them. For example if the parent needs to toggle the `disabled` state, it would be easier to do if it was it's own param.

I do like the idea of being able to pass additional attributes, maybe we can decide on what's essential that should be it's own param, and then just let developers use `htmlAttributes` for the other less common attributes.

@jbalsas @brunobasto thoughts?

**Comment by jbalsas** [comment]
Hey guys, I like the idea of the attributes... I think Fernando was looking
into it though, not sure if he didn't see a way to make it happen.

One important thing to keep in mind is that these are meant to be
components that produce a faithful lexicon experience. They should be high
level and allow only what the language allows.
Free/Multipurpose/Uberconfigurable components are fine for metal. In
Quartz, however, we should restrict the APIs only to that allowed in the
component specs.

**Comment by pat270** [comment]
I think we can still provide a good Lexicon experience without having to declare attributes 1 to 1. Personally, having 1 to 1 seems a little counter productive (a lot of typing, prone to typos, and digging through code figuring out what it does). Like what Rob was saying, we don't need to bundle everything into one attribute. The ones that make sense should have their own e.g. disabled, type, value?

Being high level doesn't necessarily mean that the component can't be Free/Multipurpose/Uberconfigurable. We still need to provide ways for developers to actually do stuff with this, otherwise it just generates static markup.

**Comment by jbalsas** [comment]
Hey Patrick, no doubt we can, but that's what `metal-*` is for. Generic, reusable, configurable components for developers to do stuff with it. If we have such a component, then it should go to metal.

Quartz components need to be opinionated and very restrictive as to what they allow. In essence, yeah, they just generate static markup. Otherwise, you end up using Quartz components but creating a whole different user experience, which beats the purpose of this abstraction.

A possible path for it would be:
1. Create a `metal-button` component with all the configurable options we want
2. Create a `quartz-button` exposing a higher level API based on the allowed button states that will use `metal-button` under the hood

**Comment by fernandosouza** [comment]
Hey, guys.

Patrick, I agree with you that letting developers define CSS classes through the `elementeClasses` makes the component quite flexible. But maybe that works well for simple components like a `button`. For more complex ones, where for changing the visual the CSS class not necessarily goes into the parent element, it doesn't. And once this component is strictly related to Quartz components, this kind of abstraction make sense.

As Chema has mentioned, I'm looking for a way to additional attributes works. Soy compiler seems to have restrictions on it.

Chema, I like the idea of creating a `metal-button` component so that other teams and projects are able to use it. I thought we've been already planning to do it whenever is possible. If you all agree, I can create the repo and send the code.

Thanks for your thoughts, guys.

**Comment by jbalsas** [comment]
Yes, the plan is to create a `metal-*` whenever we want something that is ux-agnostic and is highly configurable. `metal-quartz-*` are meant to be more opinionated and allow as less deviation from the lexicon experience as possible.

The problem with a `button` is that there is very little difference between calling it passing the params and simply generating the button markup itself. We need to be careful with abstractions that are already present in the language itself.

**Comment by pat270** [comment]
Hey Chema, Fernando,

I guess this is going a bit off topic. If the plan is to create a `metal-button` component wouldn't it make sense to create that first? As it stands now, I'm unable to rely on the button component because I'm unable to pass in data attributes to the button or know what attributes I will be able to pass in.

Since it is a WIP do we just create placeholders across all the other components that will rely on it and massively change them later?

**Comment by fernandosouza** [comment]
Hey, @pat270. I'm sorry for the delay in responding.

Yes, I would be better to start by creating a `metal-button` first, but, as I've started developing in this repository I thought to be better I continue and abstract it later.

Regarding the attributes. We could also create a generic template with general attributes and use it in the components. This way allow us to write them only once. Could be `baseDOMComponent`.

cc @brunobasto, @jbalsas, @Robert-Frampton
