### ISSUE TITLE
Refactor test infrastructure

### ISSUE THREAD

**Issue by robframpton** [metal/metal-clay-components#16]
Currently we are running into some issues when running `lerna run tests`. It attempts to start up multiple instances of karma, which can cause collisions since they are starting up servers.

We also have issues with how dependencies are resolved, see discussion on #14.

The proposed solution is to run the tests from the root directory of the project similarly to how [metal.js](https://github.com/metal/metal.js/blob/master/gulpfile.js) does it.

**Comment by brunobasto** [comment]
On a side note, It is possible to run individual tests even if we run all tests from the root directory like metal does. The gulp cli bubbles up to the closest gulpfile it finds, but it saves a reference to the current working directory path. We can use that path to only include test files from within the directory the gulp cli was found.

**Comment by anitaderiane** [comment]
https://issues.liferay.com/browse/IFI-56

**Comment by fernandosouza** [comment]
Hey, guys. I want to let you updated with the news we have. @brunobasto figured out that `karma-commonjs` plugin was not resolving `symbolic links` correctly and we've stored [his fix in a fork in my Github profile](https://github.com/fernandosouza/karma-commonjs/commits/sym-links). It is working pretty well.

This karma plugin is used by `metal-karma-config`. [There is a branch in my fork](https://github.com/fernandosouza/metal-karma-config/commits/new-karma-commonjs) using the fixed `karma-commonjs` plugin version.

Probably this is not the way we want to move forward since we probably don't want to maintain `karma-commonjs` plugin and @jbalsas has started to give a try on `Jest` as a possibility of testing framework, I hope we have it, but I'm going to use this fix since nowadays tests are breaking.

Another option is trying to setup `Jest` and check if it works with `symbolic links` without workarounds. What, in my opinion, it makes total sense for Clay Components.

**Comment by jbalsas** [comment]
I think this is already covered in the latest change, since we're already using `jest` from the top.

Please, reopen if there's still anything else worth doing.

Thanks!
